//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmploymentSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmploymentSystem.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You applied for this Application Before.
        /// </summary>
        public static string DuplicateApplication {
            get {
                return ResourceManager.GetString("DuplicateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Failed .
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERAL ERROR.
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mnot valid mobile Number .
        /// </summary>
        public static string InvalidMobileNumber {
            get {
                return ResourceManager.GetString("InvalidMobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Should contain Capital letters, small letters, numbers and symbols .
        /// </summary>
        public static string InvalidPWD {
            get {
                return ResourceManager.GetString("InvalidPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Length is 15 digits.
        /// </summary>
        public static string MaxLengthIs15 {
            get {
                return ResourceManager.GetString("MaxLengthIs15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum length is 11 digits .
        /// </summary>
        public static string MinLengthIs11 {
            get {
                return ResourceManager.GetString("MinLengthIs11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found For the Inquiry.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid .
        /// </summary>
        public static string NotValidEmail {
            get {
                return ResourceManager.GetString("NotValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 8 digits.
        /// </summary>
        public static string PwdMinLentgh {
            get {
                return ResourceManager.GetString("PwdMinLentgh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Field is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preccess successeded.
        /// </summary>
        public static string Sucess {
            get {
                return ResourceManager.GetString("Sucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not registerd in the system, Go to Register .
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered an invalid username or password.
        /// </summary>
        public static string WrongData {
            get {
                return ResourceManager.GetString("WrongData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Should Apply After 24 Hours from your last application.
        /// </summary>
        public static string YouShouldApplayAfter24Hours {
            get {
                return ResourceManager.GetString("YouShouldApplayAfter24Hours", resourceCulture);
            }
        }
    }
}
